# Server Configurations
[server]
	# Server Name
	name =				"Turing Test"
	# Server Description (Max 250 Characters)
	description =		"Start turing test?"
	# Server Logo URL (Recommended Size: 150x75)
	logo =				"https://i.imgur.com/wmFhI89.png"
	# Max Players
	max_players =		64
	# Leave it blank for no password
	password =			""
	# Server IP. Leave it 0.0.0.0 for default
	ip =				"0.0.0.0"
	# Server Port (UDP forwarding needed)
	port =				7777
	# HTTP Port (TCP forwarding needed)
	http_port =			7777
	# Announce Server in the Server List
	announce =			true
	# Server Tick Rate in milliseconds (Dangerous! Server will tick at each [tick_rate] ms, affecting both Server and Client performance. 33 ms means 30 ticks per Second and is the default and recommended value)
	tick_rate =			33
	# Log Level. (1) Normal - (2) Debug - (3) Verbose
	log_level =			1

# nanos world Configurations
[world]
	# Package List (leave it blank to load all packages, this is usually useful when you have tons of packages downloaded and only wants to load one or some)
	packages = [
		"TuringTest",
	]
	# Default startup map
	map =				"PolygonCity::Rooftops"
	# Banned IPs
	banned_ips = [
		
	]
